DROP SCHEMA IF EXISTS COFFEE;
CREATE SCHEMA COFFEE;

USE COFFEE;

DROP TABLE IF EXISTS PRODUCTOS;
CREATE TABLE PRODUCTOS(
`id_producto` INT AUTO_INCREMENT NOT NULL,
`nombre_producto` VARCHAR(80),
`descripcion_producto` TEXT,
`precio` DECIMAL (10,2) , -- (PENSANDO EN USAR USD PARA ENTENDIMIENTO GLOBAL)
CONSTRAINT PK_PRODUCTOS PRIMARY KEY(id_producto)
);


DROP TABLE IF EXISTS INSUMOS;
CREATE TABLE INSUMOS(
`id_insumo` INT AUTO_INCREMENT NOT NULL,
`nombre_insumo` VARCHAR(80),
`descripcion_insumo` TEXT,
`stock_actual` INT,
`unidad` VARCHAR(50),
`stock_minimo` INT, 
CONSTRAINT PK_INSUMOS PRIMARY KEY(id_insumo)
);


DROP TABLE IF EXISTS RECETAS;
CREATE TABLE RECETAS(
`id_receta` INT AUTO_INCREMENT NOT NULL,
`id_producto`INT,
`id_insumo` INT,
`cantidad`DECIMAL(10,2),
`unidad` VARCHAR(20),
CONSTRAINT PK_RECETAS PRIMARY KEY(id_receta),
CONSTRAINT FK_RECETAS_PRODUCTOS FOREIGN KEY (id_producto)  REFERENCES PRODUCTOS(id_producto) , -- PRODUCTOS
CONSTRAINT FK_RECETAS_INSUMOS FOREIGN KEY (id_insumo) REFERENCES INSUMOS(id_insumo) -- INSUMOS
);



DROP TABLE IF EXISTS PEDIDOS;
CREATE TABLE PEDIDOS(
`id_pedido` INT AUTO_INCREMENT NOT NULL,
`fecha` DATE,
`hora` TIME,
`total` DECIMAL (10,2),
CONSTRAINT PK_PEDIDO PRIMARY KEY(id_pedido)
);



DROP TABLE IF EXISTS DETALLE_PEDIDOS;
CREATE TABLE DETALLE_PEDIDOS(
`id_detalle` INT AUTO_INCREMENT NOT NULL,
`id_pedido` INT  NOT NULL,
`id_producto` INT NOT NULL,
`cantidad` INT,
`precio_unit` DECIMAL (10,2),
CONSTRAINT PK_DETALLE PRIMARY KEY(id_detalle),
-- UNIQUE (id_pedido),
CONSTRAINT FK_DETALLE_PEDIDO FOREIGN KEY (id_pedido) REFERENCES PEDIDOS(id_pedido), -- PEDIDOS
CONSTRAINT FK_DETALLE_PRODUCTO FOREIGN KEY (id_producto) REFERENCES PRODUCTOS(id_producto) -- PRODUCTOS
);


DROP TABLE IF EXISTS MOVIM_INVENTARIO;
CREATE TABLE MOVIM_INVENTARIO(
`id_movimiento` INT AUTO_INCREMENT NOT NULL,
`tipo` ENUM('ENTRADA', 'SALIDA'), 
`id_insumo` INT NULL,
`id_producto` INT NULL,
`cantidad` DECIMAL (10,2),
`motivo` VARCHAR(200),
`fecha` DATE, 
`hora` TIME,
CONSTRAINT PK_MOVIM PRIMARY KEY(id_movimiento),
CONSTRAINT FK_MOVIM_INSUMOS FOREIGN KEY (id_insumo) REFERENCES INSUMOS(id_insumo), -- INSUMOS
CONSTRAINT FK_MOVIM_PRODUCTOS FOREIGN KEY (id_producto) REFERENCES PRODUCTOS(id_producto) -- PRODUCTOS
);









